// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addclientandrefreshtokenentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addclientandrefreshtokenentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041322214_Add client and refresh token entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
